[project]
name         = "LegendaryOS"
version      = "0.0.1"
description  = "Fedora-based immuntable OS"
author       = "LegendaryOS-Linux-System"
license      = "GPL-3.0"
base_distro  = "fedora"
base_version = 44
arch         = "x86_64"

[system]
hostname         = "legendaryos"
locale           = "pl_PL.UTF-8"
language         = "pl_PL:pl:en_US:en"
timezone         = "Europe/Warsaw"
keyboard         = "pl"
selinux          = "enforcing"
firewall         = true
services_enable  = ["sshd", "NetworkManager", "bluetooth", "cups", "fstrim.timer"]
services_disable = ["ModemManager"]

[desktop]
environment     = "kde"
display_server  = "wayland"
auto_login      = false
auto_login_user = ""

[boot]
bootloader  = "grub2"
kernel_args = "quiet splash mitigations=off"
splash      = true
timeout     = 5

[anaconda]
enabled            = true
kickstart_embed    = true
product_name       = "LegendaryOS"
product_version    = "1.0.0"
webui              = true
hide_shell         = false
default_lang       = "pl_PL.UTF-8"
default_keyboard   = "pl"
default_timezone   = "Europe/Warsaw"
root_password_lock = true
default_user       = "user"
default_user_groups = ["wheel", "audio", "video", "gamemode", "input", "render"]

[build]
output_dir   = "build/output"
cache_dir    = "build/cache"
compression  = "zstd"
iso_label    = "LEGENDARYOS_1_0"
iso_filename = "LegendaryOS-1.0.0-fedora44.x86_64.iso"
jobs         = 4
clean_build  = false

# System filesystem type — używany przez bootc-image-builder przy budowaniu ISO
# Opcje: ext4 | xfs | btrfs
#   ext4  — domyślny, najbardziej kompatybilny, sprawdzony (ZALECANY)
#   xfs   — domyślny w Fedorze, dobry dla dużych plików
#   btrfs — nowoczesny, snapshoty, kompresja (bardziej ryzykowny)
filesystem   = "ext4"

[nvidia]
enabled                = true
open_driver            = false
blacklist_nouveau      = true
enable_kms             = true
install_nvidia_settings = true
install_vaapi          = true
install_vulkan         = true
install_cuda           = false

[container]
enabled    = true
registry   = "custom"
image      = "legendaryos"
tag        = "0.0.1"
push       = false
sign_image = false
bootc_mode = true
